version: "3"

networks:
  backend:
    driver: "bridge"

volumes:
  db-data:
  redis-data:

services:

  db:
    image: postgis/postgis:10-2.5-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=service_area
    networks:
      - backend
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    container_name: redis
    command: redis-server --appendonly yes
    expose:
      - "6379"
    networks:
      - backend
    volumes:
      - redis-data:/data

  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=service_area
    volumes:
      - .:/app
    ports:
      - "5500:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend