# Generated by Django 3.2 on 2022-03-08 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20220308_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearea',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='status',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='update_date',
        ),
    ]
