# Generated by Django 3.2 on 2022-03-08 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20220308_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicearea',
            name='status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('I', 'INACTIVE')], default='A', max_length=5),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
